# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e268729c110d99f10c6be10ebf6cd6b7dde6fc3da6dbe7d0f40016ec5abf12883517dacbdc029302fb6518b91628354e929592f0f19098641ccb6b67d556b737

test:
  secret_key_base: 2eae5966428d60201d7a5c3c3596b36c5d3f6579a16be1f0fd5523d33f69de61441786e1829d6d2984044ce9915901d85afe57967a71d132dd7e70d12bd51c8d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
